// <auto-generated />
using System;
using APIWebScrappingFinerio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIWebScrappingFinerio.Migrations
{
    [DbContext(typeof(APIDBContext))]
    [Migration("20210608184241_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APIWebScrappingFinerio.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArtistId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ArtistId1")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId1");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("APIWebScrappingFinerio.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubGenre")
                        .HasColumnType("int");

                    b.Property<int?>("SubGenreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubGenreId");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("APIWebScrappingFinerio.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("APIWebScrappingFinerio.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("APIWebScrappingFinerio.Models.SubGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("SubGenres");
                });

            modelBuilder.Entity("APIWebScrappingFinerio.Models.Album", b =>
                {
                    b.HasOne("APIWebScrappingFinerio.Models.Artist", null)
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId1");
                });

            modelBuilder.Entity("APIWebScrappingFinerio.Models.Artist", b =>
                {
                    b.HasOne("APIWebScrappingFinerio.Models.SubGenre", null)
                        .WithMany("Artists")
                        .HasForeignKey("SubGenreId");
                });

            modelBuilder.Entity("APIWebScrappingFinerio.Models.Song", b =>
                {
                    b.HasOne("APIWebScrappingFinerio.Models.Album", null)
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APIWebScrappingFinerio.Models.SubGenre", b =>
                {
                    b.HasOne("APIWebScrappingFinerio.Models.Genre", null)
                        .WithMany("SubGenre")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APIWebScrappingFinerio.Models.Album", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("APIWebScrappingFinerio.Models.Artist", b =>
                {
                    b.Navigation("Albums");
                });

            modelBuilder.Entity("APIWebScrappingFinerio.Models.Genre", b =>
                {
                    b.Navigation("SubGenre");
                });

            modelBuilder.Entity("APIWebScrappingFinerio.Models.SubGenre", b =>
                {
                    b.Navigation("Artists");
                });
#pragma warning restore 612, 618
        }
    }
}
